version: '3'
services:
  jenkins:
    ports: 
      - "8098:8080"
      - "50000:50000"
    image: jenkins/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins
volumes:
  jenkins_home: {}
